### ISSUE TITLE
[BUG] give error in the time

### ISSUE THREAD

**Issue by istarengwa** [PluginBugs/Issues-ScratchIt#8] opened 2022-04-01 21:53 UTC
**Describe the bug**

Hello, I'm on version 1.1.14 of the plugin, and when I give a card to a player, it's a give, then another, still a give, when I get to the 3rd give, the plugin shows me "Item not found" then the cards already sent tell me that it no longer exists, it does exactly the same thing at each restart.

**To Reproduce**
1. /scratchit give Istarengwa shearing_sheep   (work)
2. /scratchit give Istarengwa shearing_sheep   (work)
3. /scratchit give Istarengwa shearing_sheep   (no work)

**Screenshots**
https://zupimages.net/up/22/13/tqhj.png

**Info (please complete the following information):**
 - Server version: purpur 1.18.2
 - Client version: official 1.18.2
 - Plugin version: 1.1.14

**Comment by LoneDev6** [comment] 2022-04-04 15:40
Send your full log please

**Comment by istarengwa** [comment] 2022-04-04 15:57
the file even in several pieces is too big for pastebin and here can I send it to you on discord in mp?

**Comment by LoneDev6** [comment] 2022-04-05 08:57
I can't reproduce the issue, issuing the give command multiple times doesn't trigger the problem described, very strange

**Comment by istarengwa** [comment] 2022-04-05 09:20
https://cloud.xsplit.com/c/01FZWGD7MGRKYC75TEGP34WA18

**Comment by istarengwa** [comment] 2022-04-05 09:22
https://pastebin.com/P1yNS8hT

**Comment by istarengwa** [comment] 2022-04-05 09:55
I just completely deleted the folder, and it works again, it probably comes from one of my modifications

**Comment by istarengwa** [comment] 2022-04-22 12:15
Hello, I reopen the problem, it starts again, with your configuration, at some point the players no longer have the scratched cards, the give command no longer indicates the existing cards, and the reload command breaks the plugin, have to uninstall it completely and reinstall it to make it work again

**Comment by istarengwa** [comment] 2022-04-26 23:26
hello @LoneDev6 , it took me a while, but I finally understood what breaks the plugin, on the latest version of the plugin the /scratchit reload command displays a huge error and breaks the entirety of the plugin. But I didn't understand why it broke during the day without me doing a reload, because the error is not displayed in the console. I put an old version of scratchit and I saw that when I reload itemsadder, it automatically restarts scratchit, that's when the latest version of the scratchit plugin breaks completely. hey i hope this can help you

**Comment by LoneDev6** [comment] 2022-05-06 15:28
Should be fixed in the latest version!

**Closed as completed** 2022-05-06 15:28 UTC
Labels: bug
