### ISSUE TITLE
[BUG] Problems when players fly

### ISSUE THREAD

**Issue by Kr1S-D** [PluginBugs/Issues-ScratchIt#19] opened 2022-12-08 17:12 UTC
**Describe the bug**
When a player is flying and while moving opens a scratch card there can be 2 cases:

1) does not open the scratch card for him in the scratchable form but gives him the reward

2) opens the scratcher in the scratchable form and with the right click does not let him scratch

**To Reproduce**
1) Be in active flight mode

2) While flying right click on the scratch item

3) You will get one of the 2 cases described above!

**Expected behavior**
The scratch card should appear as a map and should be scratchable.

**Screenshots**

**Info (please complete the following information):**
 - Server version: paper 1.12.2
 - Client version: 1.17.2
 - Plugin version: 1.1.19-r5

**Comment by LoneDev6** [comment] 2023-03-16 10:32
> 1. does not open the scratch card for him in the scratchable form but gives him the reward

Cannot reproduce it

> 2. opens the scratcher in the scratchable form and with the right click does not let him scratch

Fixed in the upcoming update

**Closed as completed** 2023-03-16 10:35 UTC
Labels: bug
