### ISSUE TITLE
Duplication bug

### ISSUE THREAD

**Issue by Wastinqs** [PluginBugs/Issues-ScratchIt#15] opened 2022-09-26 18:59 UTC
REDACTED

**Comment by Wastinqs** [comment] 2022-09-26 19:01
For the second glitch: It's just like this: Use scratch > immidiately open inv and select the scratch but keep it "holding" in the air, do not place it anywhere > the item changed back from a written paper to your specified scratch item and you're ready to do it again and again and again.

**Comment by LoneDev6** [comment] 2022-09-26 19:38
I'm now trying to reproduce the issue.
Anyway next time please publish a video, it's faster for me to understand.

**Comment by LoneDev6** [comment] 2022-09-26 19:45
### Report 1
Cannot reproduce, but is surely fixed.

https://user-images.githubusercontent.com/27242001/192365326-e6f9a9dd-31ef-4899-b28c-6cf51d33fccb.mp4

### Report 2

Fixed in the new update.

## Final note

Next time please use common sense and avoid reporting duplication bugs publicly.
Report them on the Discord by pinging me in a PRIVATE thread.

**Closed as completed by LoneDev6** 2022-09-26 19:45 UTC
Labels: bug

**Comment by LoneDev6** [comment] 2022-09-26 19:48
Fixed https://www.spigotmc.org/resources/%E2%9C%A8scratchit-the-best-map-minigames-creation-tool.92055/updates
